--Categories table
create table public.categories (
  id bigint generated by default as identity not null,
  category text not null,
  created_at timestamp with time zone not null default now(),
  type text not null,
  constraint categories_pkey primary key (id),
  constraint categories_category_check check (
    (
      category = any (
        array[
          'housing'::text,
          'groceries'::text,
          'transportation'::text,
          'health'::text,
          'entertainment'::text,
          'clothing'::text,
          'other'::text
        ]
      )
    )
  ),
  constraint categories_type_check check (
    (
      type = any (array['income'::text, 'expense'::text])
    )
  )
) TABLESPACE pg_default;

--Accounts table
create table public.accounts (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  name text not null,
  type text not null,
  created_at timestamp with time zone not null default now(),
  is_active boolean not null default true,
  balance numeric not null,
  constraint accounts_pkey primary key (id),
  constraint accounts_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade,
  constraint accounts_type_check check (
    (
      type = any (
        array[
          'Cash'::text,
          'debit'::text,
          'credit'::text,
          'savings'::text,
          'investments'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

--Account_transfer table
create table public.account_transfer (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  from_account_id bigint not null,
  to_account_id bigint not null,
  amount numeric not null,
  date date not null,
  created_at timestamp with time zone not null default now(),
  constraint account_transfer_pkey primary key (id),
  constraint account_transfer_from_account_id_fkey foreign KEY (from_account_id) references accounts (id),
  constraint account_transfer_to_account_id_fkey foreign KEY (to_account_id) references accounts (id),
  constraint account_transfer_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade
) TABLESPACE pg_default;

--Transactions table
create table public.transactions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null,
  account_id bigint not null,
  category_id bigint not null,
  amount numeric not null,
  date date not null,
  description text null,
  constraint transactions_pkey primary key (id),
  constraint transactions_account_id_fkey foreign KEY (account_id) references accounts (id),
  constraint transactions_category_id_fkey foreign KEY (category_id) references categories (id),
  constraint transactions_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade
) TABLESPACE pg_default;